### ISSUE TITLE
Cannot edit tables while plugin is active since the recent update

### ISSUE THREAD

**Issue by mwxgaf** [esm7/obsidian-rtl#67]
Cannot edit tables while plugin is active since new update of obsidian
When I disable the plugin everything is ok

**Comment by esm7** [comment]
Can you send a screenshot or a video showing the problem?
Also, more details will be helpful, e.g.:
1. What version of the plugin? Did you upgrade to the latest 1.1.2?
2. What mode are you using in the notes that don't work - LTR, RTL or Auto?
3. Obsidian Desktop or Mobile? Which OS?
4. What do you mean by "cannot edit" -- what happens when you try to edit? (a video or screenshot will help here, if not, at least a step-by-step explanation of what you're seeing)

**Comment by mwxgaf** [comment]
Fixed!
Strangely, I guess that was a problem with my electron version
sorry by the way

**Comment by Af4rinz** [comment]
I'm still having this issue on Obsidian 1.5.11 for Desktop (Windows) and plugin version 1.2.1 and Auto mode. The table cells can't be edited at all while the plugin is active, but I can select multiple cells with drag and drop but selecting any action like insert or delete row/column doesn't have any effect. Strangely, I can select and edit cells that only have html content in them. Disabling the plugin or using LTR/RTL modes instead of auto makes the tables functional again, but I take mixed notes and need it to be on Auto.

![image](https://github.com/esm7/obsidian-rtl/assets/23293389/7912731a-0844-468f-a360-29a73ea905b2)

**Comment by zoli** [comment]
Can you give the problematic input as a markdown text so I can reproduce it?

**Comment by Af4rinz** [comment]
This is the example from the screenshot, but even an empty table is unresponsive.

```
---
prof: 2
STR: 13
DEX: 14
CON: 13
INT: 13
WIS: 17
CHA: 11
---

| Skill           | Ability |                   Mod.                   |            Proficiency            |             Expertise             |
| --------------- | :-----: | :--------------------------------------: | :-------------------------------: | :-------------------------------: |
| Acrobatics      |   DEX   | `= floor((this.DEX - 10)/2) + this.prof` |  <input type="checkbox" checked>  | <input type="checkbox" unchecked> |
| Animal Handling |   WIS   | `= floor((this.WIS - 10)/2) + this.prof` |  <input type="checkbox" checked>  | <input type="checkbox" unchecked> |
| Arcana          |   INT   |       `= floor((this.INT - 10)/2)`       | <input type="checkbox" unchecked> | <input type="checkbox" unchecked> |
| Athletics       |   STR   | `= floor((this.STR - 10)/2) + this.prof` |  <input type="checkbox" checked>  | <input type="checkbox" unchecked> |
| Deception       |   CHA   |       `= floor((this.CHA - 10)/2)`       | <input type="checkbox" unchecked> | <input type="checkbox" unchecked> |
| History         |   INT   |       `= floor((this.INT - 10)/2)`       | <input type="checkbox" unchecked> | <input type="checkbox" unchecked> |
| Insight         |   WIS   |       `= floor((this.WIS - 10)/2)`       | <input type="checkbox" unchecked> | <input type="checkbox" unchecked> |
| Intimidation    |   CHA   |       `= floor((this.CHA - 10)/2)`       | <input type="checkbox" unchecked> | <input type="checkbox" unchecked> |
| Investigation   |   INT   |       `= floor((this.INT - 10)/2)`       | <input type="checkbox" unchecked> | <input type="checkbox" unchecked> |
| Medicine        |   WIS   |       `= floor((this.WIS - 10)/2)`       | <input type="checkbox" unchecked> | <input type="checkbox" unchecked> |
| Nature          |   WIS   |       `= floor((this.WIS - 10)/2)`       | <input type="checkbox" unchecked> | <input type="checkbox" unchecked> |
| Perception      |   WIS   | `= floor((this.WIS - 10)/2) + this.prof` |  <input type="checkbox" checked>  | <input type="checkbox" unchecked> |
```

**Comment by zoli** [comment]
I've no problem editing "Skill" column or any other.
